<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>Hack assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\/\/</string>
			<key>comment</key>
			<string>Line comment</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.hdl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>null|M|D|A|MD|AM|AD|AMD</string>
			<key>name</key>
			<string>variable.parameter.hdl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>JGT|JLE|JEQ|JLT|JNE|JMP|JGE</string>
			<key>name</key>
			<string>keyword.other.hdl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>predefined symbols</string>
			<key>match</key>
			<string>\@R0|\@R1|\@R2|\@R3|\@R4|\@R5|\@R6|\@R7|\@R8|\@R9|\@R10|\@R11|\@R12|\@R13|\@R14|\@R15|\@SP|\@LCL|\@ARG|\@THIS|\@THAT|\@SCREEN|\@KBD</string>
			<key>name</key>
			<string>constant.language.hdl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A instruction user labels and variable symbols</string>
			<key>match</key>
			<string>\@[a-zA-Z\_\.\$\:]+[a-zA-Z\_\.\$\:\d]*</string>
			<key>name</key>
			<string>constant.character.hdl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>goto symbol</string>
			<key>match</key>
			<string>\([a-zA-Z\_\.\$\:]+[a-zA-Z\_\.\$\:\d]*\)</string>
			<key>name</key>
			<string>entity.name.function.hdl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hack_assembler</string>
	<key>uuid</key>
	<string>f861d637-283f-43ad-87c2-621cc67cd130</string>
</dict>
</plist>
